### ISSUE TITLE
Move letter-spacing and word-spacing from CSS to options

### ISSUE THREAD

**Issue by jukkae** [snaekobbi/pipeline-mod-celia#8]
Moving the following book properties from CSS to options would make the system more user-friendly:
- Letter spacing and word spacing. The end user can be provided with just values "normal" and "wide" (or something), with "wide" corresponding to `letter-spacing: 1` and `word-spacing: 3`.

**Comment by bertfrees** [comment]
OK makes sense. You know how to do this?

**Comment by bertfrees** [comment]
`maximum-number-of-sheets` and `minimum-number-of-sheets` exists already, and are implemented in the generic script.

Letter/word-spacing will be a new option. Also the option for bypassing typography (https://github.com/snaekobbi/pipeline-mod-celia/issues/9) will be a new one.

In order to be able to add new options to your Celia script and pass them to the CSS stylesheet and the translator, we need to invoke the lower-level steps `px:dtbook-to-pef.convert` and `pef:store` directly instead of `px:dtbook-to-pef`. I'll first do that change.

**Comment by jukkae** [comment]
I'll take care of this. Note-to-self: see https://github.com/snaekobbi/pipeline-mod-dedicon/commit/fa38597ece4d46c1c62440fd46b705a65f3cc35f

**Comment by jukkae** [comment]
Fixed in https://github.com/snaekobbi/pipeline-mod-celia/commit/dc9622d58c8c41d66e4d21d0247d778156ef4c4e
